-- SEQUENCES FOR TABLES

CREATE SEQUENCE seq_magasin START WITH 1;
CREATE SEQUENCE seq_pompiste START WITH 1;
CREATE SEQUENCE seq_pompe START WITH 1;
CREATE SEQUENCE seq_cuve START WITH 1;
CREATE SEQUENCE seq_unit START WITH 1;
CREATE SEQUENCE seq_product START WITH 1;
CREATE SEQUENCE seq_counter START WITH 1;
CREATE SEQUENCE seq_typetransaction START WITH 1;
CREATE SEQUENCE seq_fournisseur START WITH 1;